version: "3.11"

services:
  djangogramm:
    user: "root"
    image: djangogramm_docker:latest
    container_name: djangogramm_docker

    volumes:
      - static_volume:/djangogramm/static
      - media_volume:/djangogramm/media
    env_file:
      - ./.env
    command: >
      bash -c 'npx webpack --config webpack.config.js --mode production && python3 manage.py collectstatic --settings=djangogramm.settings.prod --noinput && python3 manage.py makemigrations --settings=djangogramm.settings.prod && python3 manage.py migrate --settings=djangogramm.settings.prod && waitress-serve --port=8000 djangogramm.wsgi:application'

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: djangogramm_nginx
    image: djangogramm_nginx
    volumes:
      - static_volume:/djangogramm/static
      - media_volume:/djangogramm/media
    depends_on:
      - djangogramm
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"


volumes:
  static_volume:
  media_volume:
